In [2]:
import pandas as pd
import numpy as np

In [3]:
data_url = "../iris-data.csv"
df1 = pd.read_csv(data_url)

In [4]:
df1

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,2.3,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   150 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   145 non-null    float64
 4   class            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df1["class"].unique()

array(['Iris-setosa', 'Iris-setossa', 'Iris-versicolor', 'versicolor',
       'Iris-virginica'], dtype=object)

In [7]:
df_columns = ["sepal_length_cm", "sepal_width_cm", "petal_length_cm", "class"]

In [8]:

# Checking nulls in each column
for x in df_columns:
    nan_count = df1[x].isna().sum()
    print("Column " + x + " :")
    print(nan_count)

Column sepal_length_cm :
0
Column sepal_width_cm :
0
Column petal_length_cm :
0
Column class :
0

In [9]:
df1.head(25)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
7,5.0,3.4,1.5,NaN,Iris-setosa
8,4.4,2.9,1.4,NaN,Iris-setosa
9,4.9,3.1,1.5,NaN,Iris-setosa
10,5.4,3.7,1.5,NaN,Iris-setosa
11,4.8,3.4,1.6,NaN,Iris-setosa
12,4.8,3.0,1.4,0.1,Iris-setosa
13,5.7,3.0,1.1,0.1,Iris-setosa
14,5.8,4.0,1.2,0.2,Iris-setosa
15,5.7,4.4,1.5,0.4,Iris-setosa
16,5.4,3.9,1.3,0.4,Iris-setosa
17,5.1,3.5,1.4,0.3,Iris-setosa
18,5.7,3.8,1.7,0.3,Iris-setossa
19,5.1,3.8,1.5,0.3,Iris-setosa
20,5.4,3.4,1.7,0.2,Iris-setosa
21,5.1,3.7,1.5,0.4,Iris-setosa
22,4.6,3.6,1.0,0.2,Iris-setosa
23,5.1,3.3,1.7,0.5,Iris-setosa
24,4.8,3.4,1.9,0.2,Iris-setosa

In [10]:
df1.describe()

       sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      145.000000
mean          5.644627        3.054667         3.758667        1.236552
std           1.312781        0.433123         1.764420        0.755058
min           0.055000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.400000
50%           5.700000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [11]:
df1 = pd.get_dummies(df1, columns=['class'], prefix='class')

In [12]:
df1

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class_Iris-setosa,class_Iris-setossa,class_Iris-versicolor,class_Iris-virginica,class_versicolor
0,5.1,3.5,1.4,0.2,True,False,False,False,False
1,4.9,3.0,1.4,0.2,True,False,False,False,False
2,4.7,3.2,1.3,0.2,True,False,False,False,False
3,4.6,3.1,1.5,0.2,True,False,False,False,False
4,5.0,3.6,1.4,0.2,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,False,True,False
146,6.3,2.5,5.0,2.3,False,False,False,True,False
147,6.5,3.0,5.2,2.0,False,False,False,True,False
148,6.2,3.4,5.4,2.3,False,False,False,True,False
149,5.9,3.0,5.1,1.8,False,False,False,True,False

In [13]:
# Checking nulls
total_nulls = df1.isnull().sum()

In [14]:
print(total_nulls)

sepal_length_cm          0
sepal_width_cm           0
petal_length_cm          0
petal_width_cm           5
class_Iris-setosa        0
class_Iris-setossa       0
class_Iris-versicolor    0
class_Iris-virginica     0
class_versicolor         0
dtype: int64

In [15]:
# Filling nulls with median
df1["petal_width_cm"] = df1["petal_width_cm"].fillna(df1["petal_width_cm"].median())

In [16]:
total_nulls = df1.isnull().sum()

In [17]:
# Checking if there are nulls
print(total_nulls)

sepal_length_cm          0
sepal_width_cm           0
petal_length_cm          0
petal_width_cm           0
class_Iris-setosa        0
class_Iris-setossa       0
class_Iris-versicolor    0
class_Iris-virginica     0
class_versicolor         0
dtype: int64

In [18]:
# Checking the new value of the nulls
df1.head(25)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class_Iris-setosa,class_Iris-setossa,class_Iris-versicolor,class_Iris-virginica,class_versicolor
0,5.1,3.5,1.4,0.2,True,False,False,False,False
1,4.9,3.0,1.4,0.2,True,False,False,False,False
2,4.7,3.2,1.3,0.2,True,False,False,False,False
3,4.6,3.1,1.5,0.2,True,False,False,False,False
4,5.0,3.6,1.4,0.2,True,False,False,False,False
5,5.4,3.9,1.7,0.4,True,False,False,False,False
6,4.6,3.4,1.4,0.3,True,False,False,False,False
7,5.0,3.4,1.5,1.3,True,False,False,False,False
8,4.4,2.9,1.4,1.3,True,False,False,False,False
9,4.9,3.1,1.5,1.3,True,False,False,False,False
10,5.4,3.7,1.5,1.3,True,False,False,False,False
11,4.8,3.4,1.6,1.3,True,False,False,False,False
12,4.8,3.0,1.4,0.1,True,False,False,False,False
13,5.7,3.0,1.1,0.1,True,False,False,False,False
14,5.8,4.0,1.2,0.2,True,False,False,False,False
15,5.7,4.4,1.5,0.4,True,False,False,False,False
16,5.4,3.9,1.3,0.4,True,False,False,False,False
17,5.1,3.5,1.4,0.3,True,False,False,False,False
18,5.7,3.8,1.7,0.3,False,True,False,False,False
19,5.1,3.8,1.5,0.3,True,False,False,False,False
20,5.4,3.4,1.7,0.2,True,False,False,False,False
21,5.1,3.7,1.5,0.4,True,False,False,False,False
22,4.6,3.6,1.0,0.2,True,False,False,False,False
23,5.1,3.3,1.7,0.5,True,False,False,False,False
24,4.8,3.4,1.9,0.2,True,False,False,False,False

In [19]:
df1 = df1.astype(int)

In [20]:
df1

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class_Iris-setosa,class_Iris-setossa,class_Iris-versicolor,class_Iris-virginica,class_versicolor
0,5,3,1,0,1,0,0,0,0
1,4,3,1,0,1,0,0,0,0
2,4,3,1,0,1,0,0,0,0
3,4,3,1,0,1,0,0,0,0
4,5,3,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
145,6,3,5,2,0,0,0,1,0
146,6,2,5,2,0,0,0,1,0
147,6,3,5,2,0,0,0,1,0
148,6,3,5,2,0,0,0,1,0
149,5,3,5,1,0,0,0,1,0

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sepal_length_cm        150 non-null    int32
 1   sepal_width_cm         150 non-null    int32
 2   petal_length_cm        150 non-null    int32
 3   petal_width_cm         150 non-null    int32
 4   class_Iris-setosa      150 non-null    int32
 5   class_Iris-setossa     150 non-null    int32
 6   class_Iris-versicolor  150 non-null    int32
 7   class_Iris-virginica   150 non-null    int32
 8   class_versicolor       150 non-null    int32
dtypes: int32(9)
memory usage: 5.4 KB